dependencies:
  - name: postgresql
    alias: db
    version: 3.15.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    alias: cache
    version: 5.0.0
    repository: https://kubernetes-charts.storage.googleapis.com/

